name: API CI

on:
  push:
    branches:
      - main
    paths:
      - "week3/api/**"
      - ".forgejo/workflows/api-ci.yaml"
    
  pull_request:
    branches:
      - main
    paths:
      - "week3/api/**"
      - ".forgejo/workflows/api-ci.yaml"

  workflow_dispatch:

concurrency:
  group: api-week3-${{ forgejo.ref }}
  cancel-in-progress: false


env:
  REGISTRY: registry.onstackit.cloud
  IMAGE_REPOSITORY: level3_julie/cloud3-api
  IMAGE_TAG: ${{ forgejo.sha }} # versiong every image with a commit


jobs:
  api-ci:
    name: Test, build and publish
    runs-on: stackit-ubuntu-22

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: week3/api/go.mod
          cache-dependency-path: week3/api/go.sum

      - name: Run Go tests
        working-directory: week3/api
        run: go test -v ./...

      - name: Compile API
        working-directory: week3/api
        run: go build ./...

      - name: Check Docker availability
        if: ${{ success() && forgejo.ref == 'refs/heads/main' && forgejo.event_name != 'pull_request' }}
        run: docker version

      - name: Login to STACKIT Container Registry
        if: ${{ success() && forgejo.ref == 'refs/heads/main' && forgejo.event_name != 'pull_request' }}
        env:
          REGISTRY_USERNAME: ${{ secrets.STACKIT_REGISTRY_USERNAME }}
          REGISTRY_TOKEN: ${{ secrets.STACKIT_REGISTRY_TOKEN }}
        run: |
          printf '%s' "$REGISTRY_TOKEN" |
            docker login "$REGISTRY" \
              --username "$REGISTRY_USERNAME" \
              --password-stdin

      - name: Build container image
        if: ${{ success() && forgejo.ref == 'refs/heads/main' && forgejo.event_name != 'pull_request' }}
        run: |
          docker build \
            --tag "$REGISTRY/$IMAGE_REPOSITORY:$IMAGE_TAG" \
            week3/api

      - name: Push container image
        if: ${{ success() && forgejo.ref == 'refs/heads/main' && forgejo.event_name != 'pull_request' }}
        run: |
          docker push "$REGISTRY/$IMAGE_REPOSITORY:$IMAGE_TAG"

      - name: Update GitOps manifest
        if: ${{ success() && forgejo.ref == 'refs/heads/main' && forgejo.event_name != 'pull_request' }}
        run: |
          IMAGE="$REGISTRY/$IMAGE_REPOSITORY:$IMAGE_TAG"

          sed -i \
            "s#image: $REGISTRY/$IMAGE_REPOSITORY:.*#image: $IMAGE#" \
            week3/deploy/ske.yaml

          grep "image:" week3/deploy/ske.yaml

      - name: Commit GitOps manifest
        if: ${{ success() && forgejo.ref == 'refs/heads/main' && forgejo.event_name != 'pull_request' }}
        run: |
          if git diff --quiet -- week3/deploy/ske.yaml; then
            echo "Deployment manifest has not changed."
            exit 0
          fi

          git config user.name "forgejo-actions"
          git config user.email "forgejo-actions@local"

          git add week3/deploy/ske.yaml
          git commit -m "deploy(api): update image to $IMAGE_TAG"
          git push origin HEAD:main
      
      # remove Registry login 
      - name: Logout from Registry
        if: ${{ always() && forgejo.ref == 'refs/heads/main' && forgejo.event_name != 'pull_request' }}
        run: docker logout "$REGISTRY" || true



