apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: week3-api
  namespace: argocd

spec:
  project: default

  source:
    repoURL: ssh://git@ssh.level3.git.onstackit.cloud/LEVEL3/julie.git
    targetRevision: main
    path: week3/deploy

  destination:
    server: https://kubernetes.default.svc
    namespace: postgres-demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true


# Git 仓库在哪里
# 需要监控哪个目录
# 部署到哪个 Kubernetes Cluster
# 部署到哪个 Namespace
# 是否自动同步