//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for LoginResponseTokenType.
const (
	Bearer LoginResponseTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the LoginResponseTokenType enum.
func (e LoginResponseTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	Admin UserRole = "admin"
	User  UserRole = "user"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case User:
		return true
	default:
		return false
	}
}

// ConnectionInfo defines model for ConnectionInfo.
type ConnectionInfo struct {
	Database string `json:"database"`

	// Host Cluster-internal read-write Service host
	//
	// Example: db-k9zhw-rw
	Host string `json:"host"`

	// Password Generated database password; do not log or commit it
	Password string `json:"password"`
	Port     string `json:"port"`

	// Uri PostgreSQL connection URI
	//
	// Example: postgresql://app:REDACTED@db-k9zhw-rw.postgres-demo:5432/app
	Uri      *string `json:"uri,omitempty"`
	Username string  `json:"username"`
}

// CreateInstanceRequest defines model for CreateInstanceRequest.
type CreateInstanceRequest struct {
	// Cpu Initial CPU request for each PostgreSQL Pod
	//
	// Example: 500m
	Cpu *string `json:"cpu,omitempty"`

	// Instances Example: 1
	Instances int `json:"instances"`

	// Name Example: pet-health-database
	Name string `json:"name"`

	// Storage Initial storage size for each PostgreSQL instance
	//
	// Example: 5Gi
	Storage *string `json:"storage,omitempty"`
}

// DBInstance defines model for DBInstance.
type DBInstance struct {
	// Cpu CPU request for each PostgreSQL Pod
	//
	// Example: 500m
	Cpu string `json:"cpu"`

	// CreatedAt Example: 2026-08-05T11:36:16Z
	CreatedAt time.Time `json:"createdAt"`

	// Id Example: db-k9zhw
	Id string `json:"id"`

	// Instances Example: 2
	Instances int `json:"instances"`

	// Name Example: pet-health-database
	Name string `json:"name"`

	// Status Example: Cluster in healthy state
	Status string `json:"status"`

	// Storage Storage size allocated to each PostgreSQL instance
	//
	// Example: 5Gi
	Storage string `json:"storage"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error Example: instance not found
	Error string `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Status Example: ok
	Status string `json:"status"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Password Example: admin-pass
	Password string `json:"password"`

	// Username Example: admin
	Username string `json:"username"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	// AccessToken Signed JWT access token
	AccessToken string `json:"accessToken"`

	// ExpiresIn Token lifetime in seconds
	//
	// Example: 3600
	ExpiresIn int `json:"expiresIn"`

	// Role Example: user
	Role UserRole `json:"role"`

	// TokenType Example: Bearer
	TokenType LoginResponseTokenType `json:"tokenType"`
}

// LoginResponseTokenType Example: Bearer
type LoginResponseTokenType string

// PatchInstanceRequest defines model for PatchInstanceRequest.
type PatchInstanceRequest struct {
	// Cpu CPU request for each PostgreSQL Pod, not API Pods.
	//
	// Example: 500m
	Cpu *string `json:"cpu,omitempty"`

	// Instances Example: 3
	Instances *int `json:"instances,omitempty"`

	// Name Example: production-database
	Name *string `json:"name,omitempty"`

	// Storage Desired storage size. Storage can only be increased.
	//
	// Example: 5Gi
	Storage *string `json:"storage,omitempty"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// Password Password must contain at least one uppercase letter, one lowercase letter, one number, and one special character.
	Password string `json:"password"`
	Username string `json:"username"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	// CreatedAt Example: 2026-08-13T10:00:00Z
	CreatedAt time.Time `json:"createdAt"`

	// Id Example: 550e8400-e29b-41d4-a716-446655440000
	Id openapi_types.UUID `json:"id"`

	// Role Example: user
	Role UserRole `json:"role"`

	// Username Example: alice
	Username string `json:"username"`
}

// UserRole Example: user
type UserRole string

// InstanceID Example: db-k9zhw
type InstanceID = string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// UnsupportedMediaType defines model for UnsupportedMediaType.
type UnsupportedMediaType = ErrorResponse

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = RegisterRequest

// CreateInstanceJSONRequestBody defines body for CreateInstance for application/json ContentType.
type CreateInstanceJSONRequestBody = CreateInstanceRequest

// PatchInstanceJSONRequestBody defines body for PatchInstance for application/json ContentType.
type PatchInstanceJSONRequestBody = PatchInstanceRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login Log in
	// (POST /api/v1/auth/login)
	Login(w http.ResponseWriter, r *http.Request)

	// (POST /api/v1/auth/register)
	RegisterUser(w http.ResponseWriter, r *http.Request)
	// GetHealth Check API health
	// (GET /api/v1/health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// ListInstances List managed PostgreSQL instances
	// (GET /api/v1/instances)
	ListInstances(w http.ResponseWriter, r *http.Request)
	// CreateInstance Create a managed PostgreSQL instance
	// (POST /api/v1/instances)
	CreateInstance(w http.ResponseWriter, r *http.Request)
	// DeleteInstance Delete a managed PostgreSQL instance
	// (DELETE /api/v1/instances/{id})
	DeleteInstance(w http.ResponseWriter, r *http.Request, id InstanceID)
	// GetInstance Get one managed PostgreSQL instance
	// (GET /api/v1/instances/{id})
	GetInstance(w http.ResponseWriter, r *http.Request, id InstanceID)
	// PatchInstance Partially update an instance
	// (PATCH /api/v1/instances/{id})
	PatchInstance(w http.ResponseWriter, r *http.Request, id InstanceID)
	// GetInstanceConnection Get PostgreSQL connection information
	// (GET /api/v1/instances/{id}/connection)
	GetInstanceConnection(w http.ResponseWriter, r *http.Request, id InstanceID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterUser operation middleware
func (siw *ServerInterfaceWrapper) RegisterUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListInstances operation middleware
func (siw *ServerInterfaceWrapper) ListInstances(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListInstances(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateInstance operation middleware
func (siw *ServerInterfaceWrapper) CreateInstance(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateInstance(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteInstance operation middleware
func (siw *ServerInterfaceWrapper) DeleteInstance(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id InstanceID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteInstance(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetInstance operation middleware
func (siw *ServerInterfaceWrapper) GetInstance(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id InstanceID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInstance(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchInstance operation middleware
func (siw *ServerInterfaceWrapper) PatchInstance(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id InstanceID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchInstance(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetInstanceConnection operation middleware
func (siw *ServerInterfaceWrapper) GetInstanceConnection(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id InstanceID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInstanceConnection(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/auth/register", wrapper.RegisterUser)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/auth/login", wrapper.Login)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/health", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/instances", wrapper.ListInstances)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/instances", wrapper.CreateInstance)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/instances/{id}", wrapper.DeleteInstance)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/instances/{id}", wrapper.GetInstance)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/api/v1/instances/{id}", wrapper.PatchInstance)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/instances/{id}/connection", wrapper.GetInstanceConnection)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Fpfc9u4Ef8qGLaP+kPZsptTX5rYSapr7qra8txMEz9AxErEhQR4AGhHyei7dxYgJZCCIllWkuuMH0wK",
	"2F3s/vDbxRJfokTmhRQgjI5GX6KCKpqDAWWfxkIbKhIYX+MTA50oXhguRTSK/lXOQAkwoEkOhjJqaE/Q",
	"HIicE5MCucpkyX6lhj/A5C25ykptQEWdiOPkgpo06kQ4PhpFnEWdSMEfJVfAopFRJXQinaSQU9QLn2he",
	"ZDiQzboff/qcPkadyCwLfKON4mIRrVYrlKALKTRY019RdgN/lKANPiVSGBD2X1oUGU8orqL/u8aleBq+",
	"RKCUVGiTeKAZZ0Q5IWQm2TJa+Wb9VcE8GkV/6W882He/6v5rlHJT2YPWrTrRG6lmnDEQxxk0X08/3opO",
	"K4bTFAgtTQrCoAXASKlBESZBEyENSekDkAJUzrXmUpC5VMSkXBNZgLIWozFjYUAJmt2CegD12tl7nM+d",
	"IKKtJOLen265LwVZq1ivgMwpz4Chml+leSNLwY613m0W67m5lfMsvNwJDI1U/DMcaVHpSzihGzeIQf9x",
	"Teq9Syw+gNAkAa2JkR/B/l5tpsiuSpdFIZUB9gswTqd2Hx+zuis3o4sSUAm6fWvqMyKwnmr55EoKAQkK",
	"Hou5tFSpEEOGO75B/ptRbS1scVMnSqWjoaYfK07srjGpgLLuo+IGCO4lngCxMzsBCuyqAAt2ooJq/SgV",
	"29b2FgQiHhipTSX14L8TJq37MrnAECYyz7khHDXPpcqpsZRdSQ5plcoEF14qvm3JRGqzUHD7n3ckWXuV",
	"3N2MGwst3Cj9Rzbq92lRjG5eX7+8mr6+/ofngl49qssgl6OL4fkZjvXtRhMCJiPRufSzZfbKT0bvoyoE",
	"do2dTZw9EZ7b79eq5Ox3SAyqulJADdS51MtKlDGOa6fZxMPSnGYaOi14JUXpHDmnZYbLOruI86i9M8eC",
	"G04zcjW5Wycu5GygSUo8t08ka/j6IrbCci7egViYNBoNAi6rCU43NuTAzuN5mfuzENMLsORde9kLLZhu",
	"CjQzaddz5x7t2khFF9D0wuAt3+mEagLR/DMEvVCvp+kKK/GrtrTwUUFg450QBq5f1fHfpo51bBvkcFwI",
	"t9yWWPCxl6YZgrP47LIbv+jGF9PBYHR+ORpc/tffNYwa6BpuV7YNBHZoWbYLNGenAk0AJtSUTWU10RIu",
	"iJOwJDhsx3wPZn5Abn040SyTrmAy8im4+jqSbB28BaeNTR0LlfUa/eCGMNdMaVuwg7pQ2xgZKGH22eyk",
	"hNT/07p6t/5QpOTHvQqraSGN7+SCC49fm/r81LjRSFnORRd/25Hs9tCSn0daUp/II4emk2qVu9zqaq8p",
	"ll4BEPOFAEZ+/m3aqNFCGwE+FVyBHgekWOEk43NAhsBtpSGRgmkf8eeXcRza2Uq6Mu5rxdidBnWD41ad",
	"yBpYV4kgkDHeR6+AKrCw2/i8erfPzb5/fOn+iisrQ96fUJOkT83lORf+20HnRBmgYzfqy8kYH3TvZDn9",
	"/Ah6VpKVtpI7Nqf7a78Gbc8Tfg7vkZqCEyqIFNmSzBB8SIIaWO+INL4V3RtYcEwVB5FIq6qtfiF5qQ0W",
	"toZyQaghGVBtiBRAyqIAlWDlnYExoDr2bSYfA29Fmc/wfyqYfdYFJFjVJClVNDGgeh/ELsain+pVXw6b",
	"Tjh7ViV8KEPZ7buToPZUJIPz6SAexfh3fEVycRHDi2Ecd+Hsp1l3OGDDLv3b4LI7HF5eXlwMh3Ecx41D",
	"QsmDB5unktWObJDxBA7L/p6Lre59OX6t3CPHOvmgrCZF2jchOzQkpeJmeYtrcmGaWTrFs/7m6U3tr59/",
	"m27V3ZhUFJhSYYaZLcnk37dT0qcF7z8M+rQ0aT/DzBVVx2q0YNai7NSYwnUceHXIbqq4eX07tXSHfFgo",
	"+cA1l4KLhd0mORV0gQ/N1qN/3HSFoP4gpCCbBqbbSoabqlqUJTsnv6A0YP70lxM8oj6A0s6cuDfoxRgF",
	"WYCgBY9G0Xkv7p3b/WFS68aAA3BHBBsCXmMFCCV4pHUNOVydcy2hW8kbiW/dzRqzaOQqhKqlCtq8kmx5",
	"QIvlsD5Jo8ZaNTFsVAntPuxZHJ9a9+7OlB1AdGm9My8zjM3QGRCSuza073WL7ZTB/il3rebacHBxyKRA",
	"92vVwWS9f3Koz+pv3mj0/r4T6TLPqVo6bxCLA0MXGomh2biL7nFyA5+qSn8+RJvQqhPknWOSb4Gwdg4+",
	"CGSDk6lvJK8AxvB3UjuqCv0xEPtpe//fVeRPaKaAsiWBT1wbfVKA+DF3h2GUu4BArN+CcWe46Bvu6dYp",
	"MdRunoxtj7kUop2u2oi/SiH5aBNEWhteY79aSWP9jeI36IJ3XJuxdxJ/lhu4gVzv84fXKNoUqFQpugz5",
	"Zm0beQQFmCMUhwcsnNccmC2Pp7T4fP+kN/53qefBdMNcXBuXzpsJ2G+K1IHdhOfedqJDrNXswD6Zt7yP",
	"Dx5kBuvvl6HW1MEfHsLd4e9Mej7qtlFW98+SUhuZEwValioB8kg1qcrT75ppnwzLH5ibN9xkHUXo13C9",
	"A9Yhyup/4WzlUkgGBrYxf23fNzDfAM/Zdv6pBxMrk0ux7j9gvVmsw/x9YhYP989Yf7E9XZyc346KU2dn",
	"Ht0dhvg77eF1bHHT/vA88aOC+xZcJ+aY2PpXY96HTdkM6XtXZ1b39jyYpNvQaHQTv1E9HexYfueT24HY",
	"LAtmObLBNn/apPJUDP8ZstCEKsNpli3XvhZHZ5/+5uu9V0C3OjZAmQ7cBwtcdaCC+fc3yC0kCkzvg5im",
	"sGkspVIbd6XEgGDAbCsoyTh6oj4j4Io4A1T7QXj31Kr2j2v37OTozU2Pb8nWrfskoaprczeCC9epxP//",
	"P/m7Ou8+/ZZPEvZCdd/HHpNPfCHOAUMqklKnpCpxLYprsEpV4ZMswZw4QYXvx3ir9zaqB9Zn5qjWubrZ",
	"AH5/j0nMXctzotuNt4RmhMEDZLLIQRh00MdyBonJCLJZdy7VI7WfJ0qVVa3eUb+f4UTc06MX8Ys4WnW+",
	"cs00ad+X0i4YbZmJbeB2acGb14N6+iHp1RxgFdvUXLnyS32aqzoFaEr1ptU3837Z8KT30ouJ/1YBQyE0",
	"0+jt/wUAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
