// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for LoginResponseTokenType.
const (
	Bearer LoginResponseTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the LoginResponseTokenType enum.
func (e LoginResponseTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	Admin UserRole = "admin"
	User  UserRole = "user"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case User:
		return true
	default:
		return false
	}
}

// ConnectionInfo defines model for ConnectionInfo.
type ConnectionInfo struct {
	Database string `json:"database"`

	// Host Cluster-internal read-write Service host
	//
	// Example: db-k9zhw-rw
	Host string `json:"host"`

	// Password Generated database password; do not log or commit it
	Password string `json:"password"`
	Port     string `json:"port"`

	// Uri PostgreSQL connection URI
	//
	// Example: postgresql://app:REDACTED@db-k9zhw-rw.postgres-demo:5432/app
	Uri      *string `json:"uri,omitempty"`
	Username string  `json:"username"`
}

// CreateInstanceRequest defines model for CreateInstanceRequest.
type CreateInstanceRequest struct {
	// Cpu Initial CPU request for each PostgreSQL Pod
	//
	// Example: 500m
	Cpu *string `json:"cpu,omitempty"`

	// Instances Example: 1
	Instances int `json:"instances"`

	// Name Example: pet-health-database
	Name string `json:"name"`

	// Storage Initial storage size for each PostgreSQL instance
	//
	// Example: 5Gi
	Storage *string `json:"storage,omitempty"`
}

// DBInstance defines model for DBInstance.
type DBInstance struct {
	// Cpu CPU request for each PostgreSQL Pod
	//
	// Example: 500m
	Cpu string `json:"cpu"`

	// CreatedAt Example: 2026-08-05T11:36:16Z
	CreatedAt time.Time `json:"createdAt"`

	// Id Example: db-k9zhw
	Id string `json:"id"`

	// Instances Example: 2
	Instances int `json:"instances"`

	// Name Example: pet-health-database
	Name string `json:"name"`

	// Status Example: Cluster in healthy state
	Status string `json:"status"`

	// Storage Storage size allocated to each PostgreSQL instance
	//
	// Example: 5Gi
	Storage string `json:"storage"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error Example: instance not found
	Error string `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Status Example: ok
	Status string `json:"status"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Password Example: admin-pass
	Password string `json:"password"`

	// Username Example: admin
	Username string `json:"username"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	// AccessToken Signed JWT access token
	AccessToken string `json:"accessToken"`

	// ExpiresIn Token lifetime in seconds
	//
	// Example: 3600
	ExpiresIn int `json:"expiresIn"`

	// Role Example: user
	Role UserRole `json:"role"`

	// TokenType Example: Bearer
	TokenType LoginResponseTokenType `json:"tokenType"`
}

// LoginResponseTokenType Example: Bearer
type LoginResponseTokenType string

// PatchInstanceRequest defines model for PatchInstanceRequest.
type PatchInstanceRequest struct {
	// Cpu CPU request for each PostgreSQL Pod, not API Pods.
	//
	// Example: 500m
	Cpu *string `json:"cpu,omitempty"`

	// Instances Example: 3
	Instances *int `json:"instances,omitempty"`

	// Name Example: production-database
	Name *string `json:"name,omitempty"`

	// Storage Desired storage size. Storage can only be increased.
	//
	// Example: 5Gi
	Storage *string `json:"storage,omitempty"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// Password Password must contain at least one uppercase letter, one lowercase letter, one number, and one special character.
	Password string `json:"password"`
	Username string `json:"username"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	// CreatedAt Example: 2026-08-13T10:00:00Z
	CreatedAt time.Time `json:"createdAt"`

	// Id Example: 550e8400-e29b-41d4-a716-446655440000
	Id openapi_types.UUID `json:"id"`

	// Role Example: user
	Role UserRole `json:"role"`

	// Username Example: alice
	Username string `json:"username"`
}

// UserRole Example: user
type UserRole string

// InstanceID Example: db-k9zhw
type InstanceID = string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// UnsupportedMediaType defines model for UnsupportedMediaType.
type UnsupportedMediaType = ErrorResponse

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = RegisterRequest

// CreateInstanceJSONRequestBody defines body for CreateInstance for application/json ContentType.
type CreateInstanceJSONRequestBody = CreateInstanceRequest

// PatchInstanceJSONRequestBody defines body for PatchInstance for application/json ContentType.
type PatchInstanceJSONRequestBody = PatchInstanceRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login Log in
	// (POST /api/v1/auth/login)
	Login(ctx echo.Context) error

	// (POST /api/v1/auth/register)
	RegisterUser(ctx echo.Context) error
	// GetHealth Check API health
	// (GET /api/v1/health)
	GetHealth(ctx echo.Context) error
	// ListInstances List managed PostgreSQL instances
	// (GET /api/v1/instances)
	ListInstances(ctx echo.Context) error
	// CreateInstance Create a managed PostgreSQL instance
	// (POST /api/v1/instances)
	CreateInstance(ctx echo.Context) error
	// DeleteInstance Delete a managed PostgreSQL instance
	// (DELETE /api/v1/instances/{id})
	DeleteInstance(ctx echo.Context, id InstanceID) error
	// GetInstance Get one managed PostgreSQL instance
	// (GET /api/v1/instances/{id})
	GetInstance(ctx echo.Context, id InstanceID) error
	// PatchInstance Partially update an instance
	// (PATCH /api/v1/instances/{id})
	PatchInstance(ctx echo.Context, id InstanceID) error
	// GetInstanceConnection Get PostgreSQL connection information
	// (GET /api/v1/instances/{id}/connection)
	GetInstanceConnection(ctx echo.Context, id InstanceID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Login(ctx)
	return err
}

// RegisterUser converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterUser(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RegisterUser(ctx)
	return err
}

// GetHealth converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealth(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealth(ctx)
	return err
}

// ListInstances converts echo context to params.
func (w *ServerInterfaceWrapper) ListInstances(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListInstances(ctx)
	return err
}

// CreateInstance converts echo context to params.
func (w *ServerInterfaceWrapper) CreateInstance(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateInstance(ctx)
	return err
}

// DeleteInstance converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteInstance(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id InstanceID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteInstance(ctx, id)
	return err
}

// GetInstance converts echo context to params.
func (w *ServerInterfaceWrapper) GetInstance(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id InstanceID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetInstance(ctx, id)
	return err
}

// PatchInstance converts echo context to params.
func (w *ServerInterfaceWrapper) PatchInstance(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id InstanceID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PatchInstance(ctx, id)
	return err
}

// GetInstanceConnection converts echo context to params.
func (w *ServerInterfaceWrapper) GetInstanceConnection(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id InstanceID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetInstanceConnection(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(options.BaseURL+"/api/v1/auth/register", wrapper.RegisterUser, options.OperationMiddlewares["registerUser"]...)
	router.POST(options.BaseURL+"/api/v1/auth/login", wrapper.Login, options.OperationMiddlewares["login"]...)
	router.GET(options.BaseURL+"/api/v1/health", wrapper.GetHealth, options.OperationMiddlewares["getHealth"]...)
	router.GET(options.BaseURL+"/api/v1/instances", wrapper.ListInstances, options.OperationMiddlewares["listInstances"]...)
	router.POST(options.BaseURL+"/api/v1/instances", wrapper.CreateInstance, options.OperationMiddlewares["createInstance"]...)
	router.DELETE(options.BaseURL+"/api/v1/instances/:id", wrapper.DeleteInstance, options.OperationMiddlewares["deleteInstance"]...)
	router.GET(options.BaseURL+"/api/v1/instances/:id", wrapper.GetInstance, options.OperationMiddlewares["getInstance"]...)
	router.PATCH(options.BaseURL+"/api/v1/instances/:id", wrapper.PatchInstance, options.OperationMiddlewares["patchInstance"]...)
	router.GET(options.BaseURL+"/api/v1/instances/:id/connection", wrapper.GetInstanceConnection, options.OperationMiddlewares["getInstanceConnection"]...)

}

type BadRequestJSONResponse ErrorResponse

type ForbiddenJSONResponse ErrorResponse

type InternalServerErrorJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type UnauthorizedJSONResponse ErrorResponse

type UnsupportedMediaTypeJSONResponse ErrorResponse

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse LoginResponse

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Login400JSONResponse struct{ BadRequestJSONResponse }

func (response Login400JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Login401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Login415JSONResponse struct {
	UnsupportedMediaTypeJSONResponse
}

func (response Login415JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type Login500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response Login500JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterUserRequestObject struct {
	Body *RegisterUserJSONRequestBody
}

type RegisterUserResponseObject interface {
	VisitRegisterUserResponse(w http.ResponseWriter) error
}

type RegisterUser201JSONResponse UserResponse

func (response RegisterUser201JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterUser400JSONResponse struct{ BadRequestJSONResponse }

func (response RegisterUser400JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterUser409Response struct {
}

func (response RegisterUser409Response) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(409)
	return nil
}

type RegisterUser500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response RegisterUser500JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListInstancesRequestObject struct {
}

type ListInstancesResponseObject interface {
	VisitListInstancesResponse(w http.ResponseWriter) error
}

type ListInstances200JSONResponse []DBInstance

func (response ListInstances200JSONResponse) VisitListInstancesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListInstances401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListInstances401JSONResponse) VisitListInstancesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListInstances403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListInstances403JSONResponse) VisitListInstancesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListInstances500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListInstances500JSONResponse) VisitListInstancesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInstanceRequestObject struct {
	Body *CreateInstanceJSONRequestBody
}

type CreateInstanceResponseObject interface {
	VisitCreateInstanceResponse(w http.ResponseWriter) error
}

type CreateInstance201JSONResponse DBInstance

func (response CreateInstance201JSONResponse) VisitCreateInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInstance400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateInstance400JSONResponse) VisitCreateInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInstance401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateInstance401JSONResponse) VisitCreateInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInstance403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateInstance403JSONResponse) VisitCreateInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInstance415JSONResponse struct {
	UnsupportedMediaTypeJSONResponse
}

func (response CreateInstance415JSONResponse) VisitCreateInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInstance500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateInstance500JSONResponse) VisitCreateInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteInstanceRequestObject struct {
	Id InstanceID `json:"id"`
}

type DeleteInstanceResponseObject interface {
	VisitDeleteInstanceResponse(w http.ResponseWriter) error
}

type DeleteInstance202Response struct {
}

func (response DeleteInstance202Response) VisitDeleteInstanceResponse(w http.ResponseWriter) error {
	w.WriteHeader(202)
	return nil
}

type DeleteInstance401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteInstance401JSONResponse) VisitDeleteInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteInstance403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteInstance403JSONResponse) VisitDeleteInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteInstance404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteInstance404JSONResponse) VisitDeleteInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteInstance500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response DeleteInstance500JSONResponse) VisitDeleteInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstanceRequestObject struct {
	Id InstanceID `json:"id"`
}

type GetInstanceResponseObject interface {
	VisitGetInstanceResponse(w http.ResponseWriter) error
}

type GetInstance200JSONResponse DBInstance

func (response GetInstance200JSONResponse) VisitGetInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstance401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetInstance401JSONResponse) VisitGetInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstance403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetInstance403JSONResponse) VisitGetInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstance404JSONResponse struct{ NotFoundJSONResponse }

func (response GetInstance404JSONResponse) VisitGetInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstance500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetInstance500JSONResponse) VisitGetInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PatchInstanceRequestObject struct {
	Id   InstanceID `json:"id"`
	Body *PatchInstanceJSONRequestBody
}

type PatchInstanceResponseObject interface {
	VisitPatchInstanceResponse(w http.ResponseWriter) error
}

type PatchInstance200JSONResponse DBInstance

func (response PatchInstance200JSONResponse) VisitPatchInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PatchInstance400JSONResponse struct{ BadRequestJSONResponse }

func (response PatchInstance400JSONResponse) VisitPatchInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PatchInstance401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PatchInstance401JSONResponse) VisitPatchInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PatchInstance403JSONResponse struct{ ForbiddenJSONResponse }

func (response PatchInstance403JSONResponse) VisitPatchInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type PatchInstance404JSONResponse struct{ NotFoundJSONResponse }

func (response PatchInstance404JSONResponse) VisitPatchInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PatchInstance415JSONResponse struct {
	UnsupportedMediaTypeJSONResponse
}

func (response PatchInstance415JSONResponse) VisitPatchInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type PatchInstance500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response PatchInstance500JSONResponse) VisitPatchInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstanceConnectionRequestObject struct {
	Id InstanceID `json:"id"`
}

type GetInstanceConnectionResponseObject interface {
	VisitGetInstanceConnectionResponse(w http.ResponseWriter) error
}

type GetInstanceConnection200JSONResponse ConnectionInfo

func (response GetInstanceConnection200JSONResponse) VisitGetInstanceConnectionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstanceConnection401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetInstanceConnection401JSONResponse) VisitGetInstanceConnectionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstanceConnection403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetInstanceConnection403JSONResponse) VisitGetInstanceConnectionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstanceConnection404JSONResponse struct{ NotFoundJSONResponse }

func (response GetInstanceConnection404JSONResponse) VisitGetInstanceConnectionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstanceConnection409JSONResponse ErrorResponse

func (response GetInstanceConnection409JSONResponse) VisitGetInstanceConnectionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstanceConnection500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetInstanceConnection500JSONResponse) VisitGetInstanceConnectionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Login Log in
	// (POST /api/v1/auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)

	// (POST /api/v1/auth/register)
	RegisterUser(ctx context.Context, request RegisterUserRequestObject) (RegisterUserResponseObject, error)
	// GetHealth Check API health
	// (GET /api/v1/health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// ListInstances List managed PostgreSQL instances
	// (GET /api/v1/instances)
	ListInstances(ctx context.Context, request ListInstancesRequestObject) (ListInstancesResponseObject, error)
	// CreateInstance Create a managed PostgreSQL instance
	// (POST /api/v1/instances)
	CreateInstance(ctx context.Context, request CreateInstanceRequestObject) (CreateInstanceResponseObject, error)
	// DeleteInstance Delete a managed PostgreSQL instance
	// (DELETE /api/v1/instances/{id})
	DeleteInstance(ctx context.Context, request DeleteInstanceRequestObject) (DeleteInstanceResponseObject, error)
	// GetInstance Get one managed PostgreSQL instance
	// (GET /api/v1/instances/{id})
	GetInstance(ctx context.Context, request GetInstanceRequestObject) (GetInstanceResponseObject, error)
	// PatchInstance Partially update an instance
	// (PATCH /api/v1/instances/{id})
	PatchInstance(ctx context.Context, request PatchInstanceRequestObject) (PatchInstanceResponseObject, error)
	// GetInstanceConnection Get PostgreSQL connection information
	// (GET /api/v1/instances/{id}/connection)
	GetInstanceConnection(ctx context.Context, request GetInstanceConnectionRequestObject) (GetInstanceConnectionResponseObject, error)
}

type StrictHandlerFunc func(ctx echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// Login operation middleware
func (sh *strictHandler) Login(ctx echo.Context) error {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx.Request().Context(), request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		return validResponse.VisitLoginResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RegisterUser operation middleware
func (sh *strictHandler) RegisterUser(ctx echo.Context) error {
	var request RegisterUserRequestObject

	var body RegisterUserJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterUser(ctx.Request().Context(), request.(RegisterUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RegisterUserResponseObject); ok {
		return validResponse.VisitRegisterUserResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(ctx echo.Context) error {
	var request GetHealthRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx.Request().Context(), request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		return validResponse.VisitGetHealthResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListInstances operation middleware
func (sh *strictHandler) ListInstances(ctx echo.Context) error {
	var request ListInstancesRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListInstances(ctx.Request().Context(), request.(ListInstancesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListInstances")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListInstancesResponseObject); ok {
		return validResponse.VisitListInstancesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateInstance operation middleware
func (sh *strictHandler) CreateInstance(ctx echo.Context) error {
	var request CreateInstanceRequestObject

	var body CreateInstanceJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateInstance(ctx.Request().Context(), request.(CreateInstanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateInstance")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateInstanceResponseObject); ok {
		return validResponse.VisitCreateInstanceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteInstance operation middleware
func (sh *strictHandler) DeleteInstance(ctx echo.Context, id InstanceID) error {
	var request DeleteInstanceRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteInstance(ctx.Request().Context(), request.(DeleteInstanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteInstance")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteInstanceResponseObject); ok {
		return validResponse.VisitDeleteInstanceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetInstance operation middleware
func (sh *strictHandler) GetInstance(ctx echo.Context, id InstanceID) error {
	var request GetInstanceRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetInstance(ctx.Request().Context(), request.(GetInstanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetInstance")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetInstanceResponseObject); ok {
		return validResponse.VisitGetInstanceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PatchInstance operation middleware
func (sh *strictHandler) PatchInstance(ctx echo.Context, id InstanceID) error {
	var request PatchInstanceRequestObject

	request.Id = id

	var body PatchInstanceJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PatchInstance(ctx.Request().Context(), request.(PatchInstanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchInstance")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PatchInstanceResponseObject); ok {
		return validResponse.VisitPatchInstanceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetInstanceConnection operation middleware
func (sh *strictHandler) GetInstanceConnection(ctx echo.Context, id InstanceID) error {
	var request GetInstanceConnectionRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetInstanceConnection(ctx.Request().Context(), request.(GetInstanceConnectionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetInstanceConnection")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetInstanceConnectionResponseObject); ok {
		return validResponse.VisitGetInstanceConnectionResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Fpfc9u4Ef8qGLaP+kPZsptTX5rYSapr7qra8txMEz9AxErEhQR4AGhHyei7dxYgJZCCIllWkuuMH0wK",
	"2F3s/vDbxRJfokTmhRQgjI5GX6KCKpqDAWWfxkIbKhIYX+MTA50oXhguRTSK/lXOQAkwoEkOhjJqaE/Q",
	"HIicE5MCucpkyX6lhj/A5C25ykptQEWdiOPkgpo06kQ4PhpFnEWdSMEfJVfAopFRJXQinaSQU9QLn2he",
	"ZDiQzboff/qcPkadyCwLfKON4mIRrVYrlKALKTRY019RdgN/lKANPiVSGBD2X1oUGU8orqL/u8aleBq+",
	"RKCUVGiTeKAZZ0Q5IWQm2TJa+Wb9VcE8GkV/6W882He/6v5rlHJT2YPWrTrRG6lmnDEQxxk0X08/3opO",
	"K4bTFAgtTQrCoAXASKlBESZBEyENSekDkAJUzrXmUpC5VMSkXBNZgLIWozFjYUAJmt2CegD12tl7nM+d",
	"IKKtJOLen265LwVZq1ivgMwpz4Chml+leSNLwY613m0W67m5lfMsvNwJDI1U/DMcaVHpSzihGzeIQf9x",
	"Teq9Syw+gNAkAa2JkR/B/l5tpsiuSpdFIZUB9gswTqd2Hx+zuis3o4sSUAm6fWvqMyKwnmr55EoKAQkK",
	"Hou5tFSpEEOGO75B/ptRbS1scVMnSqWjoaYfK07srjGpgLLuo+IGCO4lngCxMzsBCuyqAAt2ooJq/SgV",
	"29b2FgQiHhipTSX14L8TJq37MrnAECYyz7khHDXPpcqpsZRdSQ5plcoEF14qvm3JRGqzUHD7n3ckWXuV",
	"3N2MGwst3Cj9Rzbq92lRjG5eX7+8mr6+/ofngl49qssgl6OL4fkZjvXtRhMCJiPRufSzZfbKT0bvoyoE",
	"do2dTZw9EZ7b79eq5Ox3SAyqulJADdS51MtKlDGOa6fZxMPSnGYaOi14JUXpHDmnZYbLOruI86i9M8eC",
	"G04zcjW5Wycu5GygSUo8t08ka/j6IrbCci7egViYNBoNAi6rCU43NuTAzuN5mfuzENMLsORde9kLLZhu",
	"CjQzaddz5x7t2khFF9D0wuAt3+mEagLR/DMEvVCvp+kKK/GrtrTwUUFg450QBq5f1fHfpo51bBvkcFwI",
	"t9yWWPCxl6YZgrP47LIbv+jGF9PBYHR+ORpc/tffNYwa6BpuV7YNBHZoWbYLNGenAk0AJtSUTWU10RIu",
	"iJOwJDhsx3wPZn5Abn040SyTrmAy8im4+jqSbB28BaeNTR0LlfUa/eCGMNdMaVuwg7pQ2xgZKGH22eyk",
	"hNT/07p6t/5QpOTHvQqraSGN7+SCC49fm/r81LjRSFnORRd/25Hs9tCSn0daUp/II4emk2qVu9zqaq8p",
	"ll4BEPOFAEZ+/m3aqNFCGwE+FVyBHgekWOEk43NAhsBtpSGRgmkf8eeXcRza2Uq6Mu5rxdidBnWD41ad",
	"yBpYV4kgkDHeR6+AKrCw2/i8erfPzb5/fOn+iisrQ96fUJOkT83lORf+20HnRBmgYzfqy8kYH3TvZDn9",
	"/Ah6VpKVtpI7Nqf7a78Gbc8Tfg7vkZqCEyqIFNmSzBB8SIIaWO+INL4V3RtYcEwVB5FIq6qtfiF5qQ0W",
	"toZyQaghGVBtiBRAyqIAlWDlnYExoDr2bSYfA29Fmc/wfyqYfdYFJFjVJClVNDGgeh/ELsain+pVXw6b",
	"Tjh7ViV8KEPZ7buToPZUJIPz6SAexfh3fEVycRHDi2Ecd+Hsp1l3OGDDLv3b4LI7HF5eXlwMh3Ecx41D",
	"QsmDB5unktWObJDxBA7L/p6Lre59OX6t3CPHOvmgrCZF2jchOzQkpeJmeYtrcmGaWTrFs/7m6U3tr59/",
	"m27V3ZhUFJhSYYaZLcnk37dT0qcF7z8M+rQ0aT/DzBVVx2q0YNai7NSYwnUceHXIbqq4eX07tXSHfFgo",
	"+cA1l4KLhd0mORV0gQ/N1qN/3HSFoP4gpCCbBqbbSoabqlqUJTsnv6A0YP70lxM8oj6A0s6cuDfoxRgF",
	"WYCgBY9G0Xkv7p3b/WFS68aAA3BHBBsCXmMFCCV4pHUNOVydcy2hW8kbiW/dzRqzaOQqhKqlCtq8kmx5",
	"QIvlsD5Jo8ZaNTFsVAntPuxZHJ9a9+7OlB1AdGm9My8zjM3QGRCSuza073WL7ZTB/il3rebacHBxyKRA",
	"92vVwWS9f3Koz+pv3mj0/r4T6TLPqVo6bxCLA0MXGomh2biL7nFyA5+qSn8+RJvQqhPknWOSb4Gwdg4+",
	"CGSDk6lvJK8AxvB3UjuqCv0xEPtpe//fVeRPaKaAsiWBT1wbfVKA+DF3h2GUu4BArN+CcWe46Bvu6dYp",
	"MdRunoxtj7kUop2u2oi/SiH5aBNEWhteY79aSWP9jeI36IJ3XJuxdxJ/lhu4gVzv84fXKNoUqFQpugz5",
	"Zm0beQQFmCMUhwcsnNccmC2Pp7T4fP+kN/53qefBdMNcXBuXzpsJ2G+K1IHdhOfedqJDrNXswD6Zt7yP",
	"Dx5kBuvvl6HW1MEfHsLd4e9Mej7qtlFW98+SUhuZEwValioB8kg1qcrT75ppnwzLH5ibN9xkHUXo13C9",
	"A9Yhyup/4WzlUkgGBrYxf23fNzDfAM/Zdv6pBxMrk0ux7j9gvVmsw/x9YhYP989Yf7E9XZyc346KU2dn",
	"Ht0dhvg77eF1bHHT/vA88aOC+xZcJ+aY2PpXY96HTdkM6XtXZ1b39jyYpNvQaHQTv1E9HexYfueT24HY",
	"LAtmObLBNn/apPJUDP8ZstCEKsNpli3XvhZHZ5/+5uu9V0C3OjZAmQ7cBwtcdaCC+fc3yC0kCkzvg5im",
	"sGkspVIbd6XEgGDAbCsoyTh6oj4j4Io4A1T7QXj31Kr2j2v37OTozU2Pb8nWrfskoaprczeCC9epxP//",
	"P/m7Ou8+/ZZPEvZCdd/HHpNPfCHOAUMqklKnpCpxLYprsEpV4ZMswZw4QYXvx3ir9zaqB9Zn5qjWubrZ",
	"AH5/j0nMXctzotuNt4RmhMEDZLLIQRh00MdyBonJCLJZdy7VI7WfJ0qVVa3eUb+f4UTc06MX8Ys4WnW+",
	"cs00ad+X0i4YbZmJbeB2acGb14N6+iHp1RxgFdvUXLnyS32aqzoFaEr1ptU3837Z8KT30ouJ/1YBQyE0",
	"0+jt/wUAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
