// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Defines values for LoginResponseTokenType.
const (
	Bearer LoginResponseTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the LoginResponseTokenType enum.
func (e LoginResponseTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	Admin  UserRole = "admin"
	Viewer UserRole = "viewer"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case Viewer:
		return true
	default:
		return false
	}
}

// ConnectionInfo defines model for ConnectionInfo.
type ConnectionInfo struct {
	Database string `json:"database"`

	// Host Cluster-internal read-write Service host
	//
	// Example: db-k9zhw-rw
	Host string `json:"host"`

	// Password Generated database password; do not log or commit it
	Password string `json:"password"`
	Port     string `json:"port"`

	// Uri PostgreSQL connection URI
	//
	// Example: postgresql://app:REDACTED@db-k9zhw-rw.postgres-demo:5432/app
	Uri      *string `json:"uri,omitempty"`
	Username string  `json:"username"`
}

// CreateInstanceRequest defines model for CreateInstanceRequest.
type CreateInstanceRequest struct {
	// Cpu Initial CPU request for each PostgreSQL Pod
	//
	// Example: 500m
	Cpu *string `json:"cpu,omitempty"`

	// Instances Example: 1
	Instances int `json:"instances"`

	// Name Example: pet-health-database
	Name string `json:"name"`

	// Storage Initial storage size for each PostgreSQL instance
	//
	// Example: 5Gi
	Storage *string `json:"storage,omitempty"`
}

// DBInstance defines model for DBInstance.
type DBInstance struct {
	// Cpu CPU request for each PostgreSQL Pod
	//
	// Example: 500m
	Cpu string `json:"cpu"`

	// CreatedAt Example: 2026-08-05T11:36:16Z
	CreatedAt time.Time `json:"createdAt"`

	// Id Example: db-k9zhw
	Id string `json:"id"`

	// Instances Example: 2
	Instances int `json:"instances"`

	// Name Example: pet-health-database
	Name string `json:"name"`

	// Status Example: Cluster in healthy state
	Status string `json:"status"`

	// Storage Storage size allocated to each PostgreSQL instance
	//
	// Example: 5Gi
	Storage string `json:"storage"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error Example: instance not found
	Error string `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Status Example: ok
	Status string `json:"status"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Password Example: admin-pass
	Password string `json:"password"`

	// Username Example: admin
	Username string `json:"username"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	// AccessToken Signed JWT access token
	AccessToken string `json:"accessToken"`

	// ExpiresIn Token lifetime in seconds
	//
	// Example: 3600
	ExpiresIn int `json:"expiresIn"`

	// Role Example: viewer
	Role UserRole `json:"role"`

	// TokenType Example: Bearer
	TokenType LoginResponseTokenType `json:"tokenType"`
}

// LoginResponseTokenType Example: Bearer
type LoginResponseTokenType string

// PatchInstanceRequest defines model for PatchInstanceRequest.
type PatchInstanceRequest struct {
	// Cpu CPU request for each PostgreSQL Pod, not API Pods.
	//
	// Example: 500m
	Cpu *string `json:"cpu,omitempty"`

	// Instances Example: 3
	Instances *int `json:"instances,omitempty"`

	// Name Example: production-database
	Name *string `json:"name,omitempty"`

	// Storage Desired storage size. Storage can only be increased.
	//
	// Example: 5Gi
	Storage *string `json:"storage,omitempty"`
}

// UserRole Example: viewer
type UserRole string

// InstanceID Example: db-k9zhw
type InstanceID = string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// UnsupportedMediaType defines model for UnsupportedMediaType.
type UnsupportedMediaType = ErrorResponse

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// CreateInstanceJSONRequestBody defines body for CreateInstance for application/json ContentType.
type CreateInstanceJSONRequestBody = CreateInstanceRequest

// PatchInstanceJSONRequestBody defines body for PatchInstance for application/json ContentType.
type PatchInstanceJSONRequestBody = PatchInstanceRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login Log in
	// (POST /api/v1/auth/login)
	Login(ctx echo.Context) error
	// GetHealth Check API health
	// (GET /api/v1/health)
	GetHealth(ctx echo.Context) error
	// ListInstances List managed PostgreSQL instances
	// (GET /api/v1/instances)
	ListInstances(ctx echo.Context) error
	// CreateInstance Create a managed PostgreSQL instance
	// (POST /api/v1/instances)
	CreateInstance(ctx echo.Context) error
	// DeleteInstance Delete a managed PostgreSQL instance
	// (DELETE /api/v1/instances/{id})
	DeleteInstance(ctx echo.Context, id InstanceID) error
	// GetInstance Get one managed PostgreSQL instance
	// (GET /api/v1/instances/{id})
	GetInstance(ctx echo.Context, id InstanceID) error
	// PatchInstance Partially update an instance
	// (PATCH /api/v1/instances/{id})
	PatchInstance(ctx echo.Context, id InstanceID) error
	// GetInstanceConnection Get PostgreSQL connection information
	// (GET /api/v1/instances/{id}/connection)
	GetInstanceConnection(ctx echo.Context, id InstanceID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Login(ctx)
	return err
}

// GetHealth converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealth(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealth(ctx)
	return err
}

// ListInstances converts echo context to params.
func (w *ServerInterfaceWrapper) ListInstances(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListInstances(ctx)
	return err
}

// CreateInstance converts echo context to params.
func (w *ServerInterfaceWrapper) CreateInstance(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateInstance(ctx)
	return err
}

// DeleteInstance converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteInstance(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id InstanceID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteInstance(ctx, id)
	return err
}

// GetInstance converts echo context to params.
func (w *ServerInterfaceWrapper) GetInstance(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id InstanceID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetInstance(ctx, id)
	return err
}

// PatchInstance converts echo context to params.
func (w *ServerInterfaceWrapper) PatchInstance(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id InstanceID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PatchInstance(ctx, id)
	return err
}

// GetInstanceConnection converts echo context to params.
func (w *ServerInterfaceWrapper) GetInstanceConnection(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id InstanceID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetInstanceConnection(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(options.BaseURL+"/api/v1/auth/login", wrapper.Login, options.OperationMiddlewares["login"]...)
	router.GET(options.BaseURL+"/api/v1/health", wrapper.GetHealth, options.OperationMiddlewares["getHealth"]...)
	router.GET(options.BaseURL+"/api/v1/instances", wrapper.ListInstances, options.OperationMiddlewares["listInstances"]...)
	router.POST(options.BaseURL+"/api/v1/instances", wrapper.CreateInstance, options.OperationMiddlewares["createInstance"]...)
	router.DELETE(options.BaseURL+"/api/v1/instances/:id", wrapper.DeleteInstance, options.OperationMiddlewares["deleteInstance"]...)
	router.GET(options.BaseURL+"/api/v1/instances/:id", wrapper.GetInstance, options.OperationMiddlewares["getInstance"]...)
	router.PATCH(options.BaseURL+"/api/v1/instances/:id", wrapper.PatchInstance, options.OperationMiddlewares["patchInstance"]...)
	router.GET(options.BaseURL+"/api/v1/instances/:id/connection", wrapper.GetInstanceConnection, options.OperationMiddlewares["getInstanceConnection"]...)

}

type BadRequestJSONResponse ErrorResponse

type ForbiddenJSONResponse ErrorResponse

type InternalServerErrorJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type UnauthorizedJSONResponse ErrorResponse

type UnsupportedMediaTypeJSONResponse ErrorResponse

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse LoginResponse

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Login400JSONResponse struct{ BadRequestJSONResponse }

func (response Login400JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Login401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Login415JSONResponse struct {
	UnsupportedMediaTypeJSONResponse
}

func (response Login415JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type Login500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response Login500JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListInstancesRequestObject struct {
}

type ListInstancesResponseObject interface {
	VisitListInstancesResponse(w http.ResponseWriter) error
}

type ListInstances200JSONResponse []DBInstance

func (response ListInstances200JSONResponse) VisitListInstancesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListInstances401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListInstances401JSONResponse) VisitListInstancesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListInstances403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListInstances403JSONResponse) VisitListInstancesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListInstances500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListInstances500JSONResponse) VisitListInstancesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInstanceRequestObject struct {
	Body *CreateInstanceJSONRequestBody
}

type CreateInstanceResponseObject interface {
	VisitCreateInstanceResponse(w http.ResponseWriter) error
}

type CreateInstance201JSONResponse DBInstance

func (response CreateInstance201JSONResponse) VisitCreateInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInstance400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateInstance400JSONResponse) VisitCreateInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInstance401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateInstance401JSONResponse) VisitCreateInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInstance403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateInstance403JSONResponse) VisitCreateInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInstance415JSONResponse struct {
	UnsupportedMediaTypeJSONResponse
}

func (response CreateInstance415JSONResponse) VisitCreateInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInstance500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateInstance500JSONResponse) VisitCreateInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteInstanceRequestObject struct {
	Id InstanceID `json:"id"`
}

type DeleteInstanceResponseObject interface {
	VisitDeleteInstanceResponse(w http.ResponseWriter) error
}

type DeleteInstance202Response struct {
}

func (response DeleteInstance202Response) VisitDeleteInstanceResponse(w http.ResponseWriter) error {
	w.WriteHeader(202)
	return nil
}

type DeleteInstance401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteInstance401JSONResponse) VisitDeleteInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteInstance403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteInstance403JSONResponse) VisitDeleteInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteInstance404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteInstance404JSONResponse) VisitDeleteInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteInstance500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response DeleteInstance500JSONResponse) VisitDeleteInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstanceRequestObject struct {
	Id InstanceID `json:"id"`
}

type GetInstanceResponseObject interface {
	VisitGetInstanceResponse(w http.ResponseWriter) error
}

type GetInstance200JSONResponse DBInstance

func (response GetInstance200JSONResponse) VisitGetInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstance401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetInstance401JSONResponse) VisitGetInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstance403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetInstance403JSONResponse) VisitGetInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstance404JSONResponse struct{ NotFoundJSONResponse }

func (response GetInstance404JSONResponse) VisitGetInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstance500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetInstance500JSONResponse) VisitGetInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PatchInstanceRequestObject struct {
	Id   InstanceID `json:"id"`
	Body *PatchInstanceJSONRequestBody
}

type PatchInstanceResponseObject interface {
	VisitPatchInstanceResponse(w http.ResponseWriter) error
}

type PatchInstance200JSONResponse DBInstance

func (response PatchInstance200JSONResponse) VisitPatchInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PatchInstance400JSONResponse struct{ BadRequestJSONResponse }

func (response PatchInstance400JSONResponse) VisitPatchInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PatchInstance401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PatchInstance401JSONResponse) VisitPatchInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PatchInstance403JSONResponse struct{ ForbiddenJSONResponse }

func (response PatchInstance403JSONResponse) VisitPatchInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type PatchInstance404JSONResponse struct{ NotFoundJSONResponse }

func (response PatchInstance404JSONResponse) VisitPatchInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PatchInstance415JSONResponse struct {
	UnsupportedMediaTypeJSONResponse
}

func (response PatchInstance415JSONResponse) VisitPatchInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type PatchInstance500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response PatchInstance500JSONResponse) VisitPatchInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstanceConnectionRequestObject struct {
	Id InstanceID `json:"id"`
}

type GetInstanceConnectionResponseObject interface {
	VisitGetInstanceConnectionResponse(w http.ResponseWriter) error
}

type GetInstanceConnection200JSONResponse ConnectionInfo

func (response GetInstanceConnection200JSONResponse) VisitGetInstanceConnectionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstanceConnection401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetInstanceConnection401JSONResponse) VisitGetInstanceConnectionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstanceConnection403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetInstanceConnection403JSONResponse) VisitGetInstanceConnectionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstanceConnection404JSONResponse struct{ NotFoundJSONResponse }

func (response GetInstanceConnection404JSONResponse) VisitGetInstanceConnectionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstanceConnection409JSONResponse ErrorResponse

func (response GetInstanceConnection409JSONResponse) VisitGetInstanceConnectionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstanceConnection500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetInstanceConnection500JSONResponse) VisitGetInstanceConnectionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Login Log in
	// (POST /api/v1/auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// GetHealth Check API health
	// (GET /api/v1/health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// ListInstances List managed PostgreSQL instances
	// (GET /api/v1/instances)
	ListInstances(ctx context.Context, request ListInstancesRequestObject) (ListInstancesResponseObject, error)
	// CreateInstance Create a managed PostgreSQL instance
	// (POST /api/v1/instances)
	CreateInstance(ctx context.Context, request CreateInstanceRequestObject) (CreateInstanceResponseObject, error)
	// DeleteInstance Delete a managed PostgreSQL instance
	// (DELETE /api/v1/instances/{id})
	DeleteInstance(ctx context.Context, request DeleteInstanceRequestObject) (DeleteInstanceResponseObject, error)
	// GetInstance Get one managed PostgreSQL instance
	// (GET /api/v1/instances/{id})
	GetInstance(ctx context.Context, request GetInstanceRequestObject) (GetInstanceResponseObject, error)
	// PatchInstance Partially update an instance
	// (PATCH /api/v1/instances/{id})
	PatchInstance(ctx context.Context, request PatchInstanceRequestObject) (PatchInstanceResponseObject, error)
	// GetInstanceConnection Get PostgreSQL connection information
	// (GET /api/v1/instances/{id}/connection)
	GetInstanceConnection(ctx context.Context, request GetInstanceConnectionRequestObject) (GetInstanceConnectionResponseObject, error)
}

type StrictHandlerFunc func(ctx echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// Login operation middleware
func (sh *strictHandler) Login(ctx echo.Context) error {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx.Request().Context(), request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		return validResponse.VisitLoginResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(ctx echo.Context) error {
	var request GetHealthRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx.Request().Context(), request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		return validResponse.VisitGetHealthResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListInstances operation middleware
func (sh *strictHandler) ListInstances(ctx echo.Context) error {
	var request ListInstancesRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListInstances(ctx.Request().Context(), request.(ListInstancesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListInstances")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListInstancesResponseObject); ok {
		return validResponse.VisitListInstancesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateInstance operation middleware
func (sh *strictHandler) CreateInstance(ctx echo.Context) error {
	var request CreateInstanceRequestObject

	var body CreateInstanceJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateInstance(ctx.Request().Context(), request.(CreateInstanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateInstance")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateInstanceResponseObject); ok {
		return validResponse.VisitCreateInstanceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteInstance operation middleware
func (sh *strictHandler) DeleteInstance(ctx echo.Context, id InstanceID) error {
	var request DeleteInstanceRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteInstance(ctx.Request().Context(), request.(DeleteInstanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteInstance")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteInstanceResponseObject); ok {
		return validResponse.VisitDeleteInstanceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetInstance operation middleware
func (sh *strictHandler) GetInstance(ctx echo.Context, id InstanceID) error {
	var request GetInstanceRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetInstance(ctx.Request().Context(), request.(GetInstanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetInstance")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetInstanceResponseObject); ok {
		return validResponse.VisitGetInstanceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PatchInstance operation middleware
func (sh *strictHandler) PatchInstance(ctx echo.Context, id InstanceID) error {
	var request PatchInstanceRequestObject

	request.Id = id

	var body PatchInstanceJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PatchInstance(ctx.Request().Context(), request.(PatchInstanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchInstance")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PatchInstanceResponseObject); ok {
		return validResponse.VisitPatchInstanceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetInstanceConnection operation middleware
func (sh *strictHandler) GetInstanceConnection(ctx echo.Context, id InstanceID) error {
	var request GetInstanceConnectionRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetInstanceConnection(ctx.Request().Context(), request.(GetInstanceConnectionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetInstanceConnection")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetInstanceConnectionResponseObject); ok {
		return validResponse.VisitGetInstanceConnectionResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Fpbc9u4Ff4rGLSP1M2XTFZ9qWM7rrbZrWrLszN1/AARRyLWJMAAoLyKR/+9c8CLQIqybFlJdt8smgAO",
	"vvPhOxfwiYYqSZUEaQ0dPtGUaZaABe1+jaSxTIYwusBfHEyoRWqFknRI/51NQUuwYEgClnFmWVeyBIia",
	"ERsBOY9Vxn9lVixgfEXO48xY0DSgAgenzEY0oPg+HVLBaUA1fMmEBk6HVmcQUBNGkDBcF/5gSRrji3za",
	"efjpa/RIA2qXKT4xVgs5p6vVCmcwqZIGnOkfGL+GLxkYi79CJS1I9ydL01iEDHfR+93gVrwVnihorTTa",
	"JBcsFpzofBIyVXxJV75Zf9cwo0P6t94awV7+X9O7xFmuC3vQulVAPyo9FZyD3M+gWTV8fyuChg8nERCW",
	"2QikRQuAk8yAJlyBIVJZErEFkBR0IowRSpKZ0sRGwhCVgnYWozEjaUFLFt+AXoC+zO3dD/N8ImLcTCR/",
	"frjtnklSLVHtgMyYiIHjMr8q+1Flku9rfX5YHHIzN8+b+HIr0TVKi6+wp0WZP8MBYVwzBvEThpRnlzh+",
	"AGFhCMYQqx7A/b84TNTtymRpqrQF/gtwwSbuHO+zu/N8RAdnwEUQ9o2hb/BANdTpybmSEkKceCRnykml",
	"Rg5ZkesN6t+UGWdhQ5sCGqlchuo4FprYqTipgfHOoxYWCJ4lEQJxI4MWCezoFhUMaMqMeVSab652BRIZ",
	"D5yUppLy5X8Qrhx8sZqjC0OVJMISgSvPlE6YdZJdzNy2qtK2deOZFpuWjJWxcw03//1EwgpVcns9qm00",
	"zd8yX+Jhr8fSdHh9eXF2Prm8+KcHQbd8q8MhUcPTk+MjfNe3G01oMRmFLg8/G2av/GB0RwsXuD0Gaz97",
	"U3iw31dLqenvEFpc6lwDs1DGUi8qMc4F7p3FY49LMxYbCBr0CtMsB3LGshi3dXTaT2jzZI6ksILF5Hx8",
	"WwUu1GxgYUQ82MeK17A+7bvJEiE/gZzbiA4HLZCVAmdqB3LgxokkS/xRyOk5OPEuUfZcC7YTAYtt1PHg",
	"3LG6sUqzOdRRGFyJrSAUA4gRX6EVhXI/dSjcjM/a0uBHQYE1Om0cuPhQ+n9TOirf1sRhPxduwBY68vEz",
	"W3fBUf/oXaf/vtM/nQwGw+N3w8G7//mnhjMLHSvczjaJwF+alm0jzdGhSNNCE2az+mKl0BIhST7DkuBr",
	"W8Z7NPMdcuPTicWxyhMmq17Dq+eZ5PLgDTqtbQocVao9+s5t41w9pG3QDspEbW1kSwqzy+Z8lrbl/+Wg",
	"3r5+m6fUw84Fi2FtK35ScyE9fa2v54fGSW0J30+MJ0J28N0twW+HTPlxpTHrK3XlpeGl2PU2mPNcbIKp",
	"WAupxVwCJz//NqnlbG0HA/5IhQYzapnFTU5iMQNUDDxmBkIlufGRPX7X77eddK3ytO655OzWgL7G91YB",
	"dQaWWSNIVJA7+gGYBkfDNebFs10w+/j4s/s7LqxsQ3/MbBi9NrYnQvpPB8GBIkLgDu7ZeIQ/TPdgMf54",
	"D7nWimcus9s3xvt7vwDj6gs/pndJKckhk0TJeEmmSD4URQO8u0dY3/BuRTyPa+VZXgh4bHKueNY2t4Ew",
	"08Iub5DTOb5Tx1Asp9a/PpaS8/Nvk43UBs+pBptpPLTTJRn/52ZCeiwVvcWgh7VeL0YxoEXlghZMG6cg",
	"sjbNizpR1DH1Ja4vbyaOQUixVKuFwMpfyDlhkpOESTbHH/Xujp/R57HWfJZKknWPqPvZnS5hi4CsMn5M",
	"fsHZgPvDz8ZYBSxAm9ycfnfQ7aMnVAqSpYIO6XG33z12omgjB2MLAKiCrTWXV7sCYQSrhrzngbvLoSVs",
	"Qw+RS1XDYMTpMBfdomsFxn5QfPmCKvZlpWgtjK3qemV1Bs1W11G/f+i1txf/7gViMofOLIvRNye5AW3z",
	"Vob2vIacGzLYPeS20b84GZy+ZFBLg2EVoP7tHtzWyvIPLx3e3QfUZEnC9DJHgzgeWDY3KA713gi9x8El",
	"P/PcE42Yg3NTnVJXYPOUiX5D/zaSsrbuznjkWjqZlE3pau7+PILwwYlFVBpe4lDspLb/WmxpheCTMHbk",
	"Jb5vgkFYSMwuPLy6bK3/TGu2bMOmso08ggbUCy1ggXGpOg/xcn969493D/rot4Hfxuk1i4WxubTXxdiv",
	"QUrHrt1z7xo/psWN9YbHq1XS6/V5lBlU1wVtleCL+3ztzZgXqezgYKfQZ90my8pyNcyMVQnRYFSmQyCP",
	"zJCi4vuuqvtqWv5AnV5rkwOKsOd4vYXWbZLVexJ8lacTMVjY5PyFe17jfI08R5u5SPkycXMKJav0HnOP",
	"tHLz9/FZ/2T3iOqC5HB+ynHby0/B1ji63Q3973SGK9/iof3hceJHOfcKLFES9vKtfxN9127K+pWed1O9",
	"une1QRhtUqNWrH+j7L21IfCds/gXcjNLudPImtr8aYPKazn8Z4hCY6atYHG8rLCWe0ef3vqyzEugG9U7",
	"MG5aPr9ouVnEgtdjGLmBUIPtfpaTCNZNhkgZm9/gWpAcuGsLhLFAJMoaAXckOOCyn6X3WUjRCshL/60a",
	"vb5Y/ZZq3bi+bcu61leRQuaNX/z7r6nfJ/2f9rtUD9tRKK7XkUbLA39/khNDaRKxfJEixXUsLsmqdMFP",
	"sgR74ADVfh3t7d47qB5Z3xijGnV1vRl4d49BLP8KJp+62YQJWUw4LCBWaQLSIkAP2RRCGxNUs85M6Ufm",
	"7isyHRdtv2GvF+NAPNPD9/33fboKnvmqK2x+nmByZzTnDF0zr8NSUb+N75pF2C01wC3sQnMB5VNZzRWd",
	"AjSleLJWQ++hh7z3tNFuWd2v/h8AAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
