apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: managed-postgres
  namespace: postgres-demo
spec:
  instances: 3

  bootstrap:
    initdb:
      database: app
      owner: app

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required

  storage:
    size: 5Gi
    storageClass: premium-perf1-stackit